// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameHelloDevPO = "HELLO_DEV"

// HELLODEV mapped from table <HELLO_DEV>
type HelloDevPO struct {
	SSN_ID string    `gorm:"column:SSN_ID;not null" json:"SSN_ID"`
	SSN_DR string    `gorm:"column:SSN_DR" json:"SSN_DR"`
	SSN_NO string    `gorm:"column:SSN_NO;not null" json:"SSN_NO"`
	SEQ_NO int64     `gorm:"column:SEQ_NO" json:"SEQ_NO"`
	BLD_ID string    `gorm:"column:BLD_ID" json:"BLD_ID"`
	BLD_DT time.Time `gorm:"column:BLD_DT" json:"BLD_DT"`
	MOD_ID string    `gorm:"column:MOD_ID" json:"MOD_ID"`
	MOD_DT time.Time `gorm:"column:MOD_DT" json:"MOD_DT"`
	SYS_ID []uint8   `gorm:"column:SYS_ID;primaryKey;default:newid()" json:"SYS_ID"`
}

// TableName HELLODEV's table name
func (*HelloDevPO) TableName() string {
	return TableNameHelloDevPO
}
