// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/google/wire"
	"user/controller"
	"user/repo"
	"user/server"
	"user/service"
)

// Injectors from wire.go:

// wireApp 初始化 Kratos App
func wireApp() (*kratos.App, func(), error) {
	iHelloRepo := repo.NewHelloRepo()
	helloService := service.NewHelloService(iHelloRepo)
	helloController := controller.NewHelloController(helloService)
	httpServer := server.NewHTTPServer(helloController)
	app := newApp(httpServer)
	return app, func() {
	}, nil
}

// wire.go:

// ProviderSet 定义所有依赖
var ProviderSet = wire.NewSet(repo.NewHelloRepo, service.NewHelloService, controller.NewHelloController, server.NewHTTPServer, newApp)
