// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"user/controller"
	"user/repo"
	service2 "user/service"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp2() (*kratos.App, func(), error) {
	iHelloRepo := service.NewHelloRepo()
	helloService := service2.NewHelloService(iHelloRepo)
	helloController := Controller.NewHelloController(helloService)
	server := NewHTTPServer(helloController)
	app := newApp(server)
	return app, func() {
	}, nil
}


