// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.4
// source: api/hello.proto

package api

import (
	common "github.com/biny-go/loong/proto/common"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SaveHelloRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveHelloRequest) Reset() {
	*x = SaveHelloRequest{}
	mi := &file_api_hello_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveHelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveHelloRequest) ProtoMessage() {}

func (x *SaveHelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_hello_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveHelloRequest.ProtoReflect.Descriptor instead.
func (*SaveHelloRequest) Descriptor() ([]byte, []int) {
	return file_api_hello_proto_rawDescGZIP(), []int{0}
}

type DeleteHelloRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteHelloRequest) Reset() {
	*x = DeleteHelloRequest{}
	mi := &file_api_hello_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteHelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteHelloRequest) ProtoMessage() {}

func (x *DeleteHelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_hello_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteHelloRequest.ProtoReflect.Descriptor instead.
func (*DeleteHelloRequest) Descriptor() ([]byte, []int) {
	return file_api_hello_proto_rawDescGZIP(), []int{1}
}

type GetHelloRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHelloRequest) Reset() {
	*x = GetHelloRequest{}
	mi := &file_api_hello_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHelloRequest) ProtoMessage() {}

func (x *GetHelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_hello_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHelloRequest.ProtoReflect.Descriptor instead.
func (*GetHelloRequest) Descriptor() ([]byte, []int) {
	return file_api_hello_proto_rawDescGZIP(), []int{2}
}

type ListHelloRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListHelloRequest) Reset() {
	*x = ListHelloRequest{}
	mi := &file_api_hello_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListHelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHelloRequest) ProtoMessage() {}

func (x *ListHelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_hello_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHelloRequest.ProtoReflect.Descriptor instead.
func (*ListHelloRequest) Descriptor() ([]byte, []int) {
	return file_api_hello_proto_rawDescGZIP(), []int{3}
}

type HelloDevPOList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*HelloDevPO          `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloDevPOList) Reset() {
	*x = HelloDevPOList{}
	mi := &file_api_hello_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloDevPOList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloDevPOList) ProtoMessage() {}

func (x *HelloDevPOList) ProtoReflect() protoreflect.Message {
	mi := &file_api_hello_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloDevPOList.ProtoReflect.Descriptor instead.
func (*HelloDevPOList) Descriptor() ([]byte, []int) {
	return file_api_hello_proto_rawDescGZIP(), []int{4}
}

func (x *HelloDevPOList) GetItems() []*HelloDevPO {
	if x != nil {
		return x.Items
	}
	return nil
}

type HelloDevPO struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SSN_ID        string                 `protobuf:"bytes,1,opt,name=SSN_ID,json=SSNID,proto3" json:"SSN_ID,omitempty"`
	SSN_DR        string                 `protobuf:"bytes,2,opt,name=SSN_DR,json=SSNDR,proto3" json:"SSN_DR,omitempty"`
	SSN_NO        string                 `protobuf:"bytes,3,opt,name=SSN_NO,json=SSNNO,proto3" json:"SSN_NO,omitempty"`
	SEQ_NO        int64                  `protobuf:"varint,4,opt,name=SEQ_NO,json=SEQNO,proto3" json:"SEQ_NO,omitempty"`
	BLD_ID        string                 `protobuf:"bytes,5,opt,name=BLD_ID,json=BLDID,proto3" json:"BLD_ID,omitempty"`
	BLD_DT        int64                  `protobuf:"varint,6,opt,name=BLD_DT,json=BLDDT,proto3" json:"BLD_DT,omitempty"`
	MOD_ID        string                 `protobuf:"bytes,7,opt,name=MOD_ID,json=MODID,proto3" json:"MOD_ID,omitempty"`
	MOD_DT        int64                  `protobuf:"varint,8,opt,name=MOD_DT,json=MODDT,proto3" json:"MOD_DT,omitempty"`
	SYS_ID        []byte                 `protobuf:"bytes,9,opt,name=SYS_ID,json=SYSID,proto3" json:"SYS_ID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloDevPO) Reset() {
	*x = HelloDevPO{}
	mi := &file_api_hello_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloDevPO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloDevPO) ProtoMessage() {}

func (x *HelloDevPO) ProtoReflect() protoreflect.Message {
	mi := &file_api_hello_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloDevPO.ProtoReflect.Descriptor instead.
func (*HelloDevPO) Descriptor() ([]byte, []int) {
	return file_api_hello_proto_rawDescGZIP(), []int{5}
}

func (x *HelloDevPO) GetSSN_ID() string {
	if x != nil {
		return x.SSN_ID
	}
	return ""
}

func (x *HelloDevPO) GetSSN_DR() string {
	if x != nil {
		return x.SSN_DR
	}
	return ""
}

func (x *HelloDevPO) GetSSN_NO() string {
	if x != nil {
		return x.SSN_NO
	}
	return ""
}

func (x *HelloDevPO) GetSEQ_NO() int64 {
	if x != nil {
		return x.SEQ_NO
	}
	return 0
}

func (x *HelloDevPO) GetBLD_ID() string {
	if x != nil {
		return x.BLD_ID
	}
	return ""
}

func (x *HelloDevPO) GetBLD_DT() int64 {
	if x != nil {
		return x.BLD_DT
	}
	return 0
}

func (x *HelloDevPO) GetMOD_ID() string {
	if x != nil {
		return x.MOD_ID
	}
	return ""
}

func (x *HelloDevPO) GetMOD_DT() int64 {
	if x != nil {
		return x.MOD_DT
	}
	return 0
}

func (x *HelloDevPO) GetSYS_ID() []byte {
	if x != nil {
		return x.SYS_ID
	}
	return nil
}

var File_api_hello_proto protoreflect.FileDescriptor

const file_api_hello_proto_rawDesc = "" +
	"\n" +
	"\x0fapi/hello.proto\x12\x03api\x1a\x1cgoogle/api/annotations.proto\x1a\x19proto/common/common.proto\"\x12\n" +
	"\x10SaveHelloRequest\"\x14\n" +
	"\x12DeleteHelloRequest\"\x11\n" +
	"\x0fGetHelloRequest\"\x12\n" +
	"\x10ListHelloRequest\"7\n" +
	"\x0eHelloDevPOList\x12%\n" +
	"\x05items\x18\x01 \x03(\v2\x0f.api.HelloDevPOR\x05items\"\xdb\x01\n" +
	"\n" +
	"HelloDevPO\x12\x15\n" +
	"\x06SSN_ID\x18\x01 \x01(\tR\x05SSNID\x12\x15\n" +
	"\x06SSN_DR\x18\x02 \x01(\tR\x05SSNDR\x12\x15\n" +
	"\x06SSN_NO\x18\x03 \x01(\tR\x05SSNNO\x12\x15\n" +
	"\x06SEQ_NO\x18\x04 \x01(\x03R\x05SEQNO\x12\x15\n" +
	"\x06BLD_ID\x18\x05 \x01(\tR\x05BLDID\x12\x15\n" +
	"\x06BLD_DT\x18\x06 \x01(\x03R\x05BLDDT\x12\x15\n" +
	"\x06MOD_ID\x18\a \x01(\tR\x05MODID\x12\x15\n" +
	"\x06MOD_DT\x18\b \x01(\x03R\x05MODDT\x12\x15\n" +
	"\x06SYS_ID\x18\t \x01(\fR\x05SYSID2\xb9\x02\n" +
	"\x05Hello\x12I\n" +
	"\tSaveHello\x12\x15.api.SaveHelloRequest\x1a\x12.common.BaseResult\"\x11\x82\xd3\xe4\x93\x02\v:\x01*\"\x06/hello\x12J\n" +
	"\vDeleteHello\x12\x17.api.DeleteHelloRequest\x1a\x12.common.BaseResult\"\x0e\x82\xd3\xe4\x93\x02\b*\x06/hello\x12D\n" +
	"\bGetHello\x12\x14.api.GetHelloRequest\x1a\x12.common.BaseResult\"\x0e\x82\xd3\xe4\x93\x02\b\x12\x06/hello\x12S\n" +
	"\tListHello\x12\x15.api.ListHelloRequest\x1a\x17.common.BaseResultArray\"\x16\x82\xd3\xe4\x93\x02\x10:\x01*\"\v/hello/listB\x15\n" +
	"\x03apiP\x01Z\fuser/api;apib\x06proto3"

var (
	file_api_hello_proto_rawDescOnce sync.Once
	file_api_hello_proto_rawDescData []byte
)

func file_api_hello_proto_rawDescGZIP() []byte {
	file_api_hello_proto_rawDescOnce.Do(func() {
		file_api_hello_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_hello_proto_rawDesc), len(file_api_hello_proto_rawDesc)))
	})
	return file_api_hello_proto_rawDescData
}

var file_api_hello_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_hello_proto_goTypes = []any{
	(*SaveHelloRequest)(nil),       // 0: api.SaveHelloRequest
	(*DeleteHelloRequest)(nil),     // 1: api.DeleteHelloRequest
	(*GetHelloRequest)(nil),        // 2: api.GetHelloRequest
	(*ListHelloRequest)(nil),       // 3: api.ListHelloRequest
	(*HelloDevPOList)(nil),         // 4: api.HelloDevPOList
	(*HelloDevPO)(nil),             // 5: api.HelloDevPO
	(*common.BaseResult)(nil),      // 6: common.BaseResult
	(*common.BaseResultArray)(nil), // 7: common.BaseResultArray
}
var file_api_hello_proto_depIdxs = []int32{
	5, // 0: api.HelloDevPOList.items:type_name -> api.HelloDevPO
	0, // 1: api.Hello.SaveHello:input_type -> api.SaveHelloRequest
	1, // 2: api.Hello.DeleteHello:input_type -> api.DeleteHelloRequest
	2, // 3: api.Hello.GetHello:input_type -> api.GetHelloRequest
	3, // 4: api.Hello.ListHello:input_type -> api.ListHelloRequest
	6, // 5: api.Hello.SaveHello:output_type -> common.BaseResult
	6, // 6: api.Hello.DeleteHello:output_type -> common.BaseResult
	6, // 7: api.Hello.GetHello:output_type -> common.BaseResult
	7, // 8: api.Hello.ListHello:output_type -> common.BaseResultArray
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_hello_proto_init() }
func file_api_hello_proto_init() {
	if File_api_hello_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_hello_proto_rawDesc), len(file_api_hello_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_hello_proto_goTypes,
		DependencyIndexes: file_api_hello_proto_depIdxs,
		MessageInfos:      file_api_hello_proto_msgTypes,
	}.Build()
	File_api_hello_proto = out.File
	file_api_hello_proto_goTypes = nil
	file_api_hello_proto_depIdxs = nil
}
